### ISSUE TITLE
reinforcing-assembly.ifc IfcBuildingElementProxy - IfcReinforcingBarType association

### ISSUE THREAD

**Issue by aothms** [buildingSMART/IFC4.3.x-sample-models#5]
@jmirtsch in sample model [reinforcing-assembly.ifc](https://github.com/buildingSMART/IFC4.3.x-sample-models/blob/main/models/additional-test-cases/reinforcing-assembly/reinforcing-assembly.ifc) is there any reason why you instantiated IfcBuildingElementProxy, should they just be IfcReinforcingBar?

**Comment by aothms** [comment]
Also https://github.com/buildingSMART/IFC4.3.x-sample-models/blob/main/models/additional-test-cases/reinforcing-stirrup/reinforcing-stirrup.ifc

**Comment by jmirtsch** [comment]
The Ifc files were originally provided with instances of IfcReinforcingBar (not IfcBuildingElementProxy).  Seems they were altered in the process of publishing the spec.
I've manually corrected them and will submit a PR.
